# Generated by Django 5.2.6 on 2025-10-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='technologies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='code_snippets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='steps',
            field=models.TextField(blank=True, default=''),
        ),
    ]
